name: Deploy Chatbot

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Kill Container if exists
      run: |
        if [ "$(docker ps -q -f name=armms-pipeline)" ]; then
          docker kill armms-pipeline
        fi
    
    - name: Remove Container if exists
      run: |
        if [ "$(docker ps -aq -f name=armms-pipeline)" ]; then
          docker rm armms-pipeline
        fi
    
    - name: Add env variables
      run: |
        echo "ARMMS_SECRET=${{ secrets.ARMMS_SECRET }}" >> ./src/webui_pipeline/pipelines/.env
        echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> ./src/webui_pipeline/pipelines/.env
        echo "STORAGE_SERVER=${{ vars.STORAGE_SERVER }}" >> ./src/webui_pipeline/pipelines/.env
        echo "CACHE_EXPIRY_SECONDS=${{ vars.CACHE_EXPIRY_SECONDS }}" >> ./src/webui_pipeline/pipelines/.env
        echo "WEAVIATE_PORT=${{ vars.WEAVIATE_PORT }}" >> ./src/webui_pipeline/pipelines/.env

    - name: Build and Deploy Container
      run: |
        # A directory should be created
        docker build -t armms-pipeline ./src/webui_pipeline
        docker run -d -p 9099:9099 --name armms-pipeline --network=host armms-pipeline
